spring.application.name=gateway-service

server.port=${PORT:8080}

spring.main.web-application-type=reactive

# =========================================
# DISABLE EUREKA TEMPORARILY
# =========================================
eureka.client.enabled=false

# =========================================
# GLOBAL CORS
# =========================================
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=false

# =========================================
# SIMPLE TEST ROUTE
# =========================================
spring.cloud.gateway.routes[0].id=test
spring.cloud.gateway.routes[0].uri=https://httpbin.org
spring.cloud.gateway.routes[0].predicates[0]=Path=/test

logging.level.org.springframework.cloud.gateway=DEBUG