spring.application.name=gateway-service

# Dynamic port (local + cloud)
server.port=${PORT:8080}

# Eureka (local + deployment)
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}

# Gateway Routes 

# Auth Service (public APIs)
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=${AUTH_SERVICE_URL:lb://auth-service}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# Auth Service (protected APIs)
spring.cloud.gateway.server.webflux.routes[1].id=auth-api
spring.cloud.gateway.server.webflux.routes[1].uri=${AUTH_SERVICE_URL:lb://auth-service}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/**

# Logging
logging.level.org.springframework.cloud.gateway=INFO