spring.application.name=category-service

server.port=${PORT:8084}

# ======================================
# EUREKA
# ======================================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

# ======================================
# DATABASE
# ======================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ======================================
# SWAGGER
# ======================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html