spring.application.name=analytics-service

server.port=${PORT:8086}

# ======================================
# EUREKA
# ======================================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

# ======================================
# FEIGN TIMEOUTS
# ======================================
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000

# ======================================
# SWAGGER
# ======================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html